//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Grammar\LentoParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace LentoCore.Parser {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="LentoParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface ILentoParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.whitespace_any"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhitespace_any([NotNull] LentoParser.Whitespace_anyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.whitespace_sp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhitespace_sp([NotNull] LentoParser.Whitespace_spContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.whitespace_nl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhitespace_nl([NotNull] LentoParser.Whitespace_nlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.semi_colon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSemi_colon([NotNull] LentoParser.Semi_colonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtom([NotNull] LentoParser.AtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] LentoParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.type_namespaced"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_namespaced([NotNull] LentoParser.Type_namespacedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] LentoParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.identifier_namespaced"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier_namespaced([NotNull] LentoParser.Identifier_namespacedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.identifier_ignore"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier_ignore([NotNull] LentoParser.Identifier_ignoreContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_name([NotNull] LentoParser.Function_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.function_name_namespaced"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_name_namespaced([NotNull] LentoParser.Function_name_namespacedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.operator_infix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperator_infix([NotNull] LentoParser.Operator_infixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.operator_prefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperator_prefix([NotNull] LentoParser.Operator_prefixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.integer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInteger([NotNull] LentoParser.IntegerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.floating_point"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloating_point([NotNull] LentoParser.Floating_pointContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.number_hex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber_hex([NotNull] LentoParser.Number_hexContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.number_binary"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumber_binary([NotNull] LentoParser.Number_binaryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.numerical"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumerical([NotNull] LentoParser.NumericalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.string"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitString([NotNull] LentoParser.StringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.character"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharacter([NotNull] LentoParser.CharacterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.typed_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTyped_identifier([NotNull] LentoParser.Typed_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.tuple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTuple([NotNull] LentoParser.TupleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.tuple_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTuple_type([NotNull] LentoParser.Tuple_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList([NotNull] LentoParser.ListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.list_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList_type([NotNull] LentoParser.List_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.map_element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMap_element([NotNull] LentoParser.Map_elementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.map"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMap([NotNull] LentoParser.MapContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.map_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMap_type([NotNull] LentoParser.Map_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] LentoParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_call([NotNull] LentoParser.Function_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.function_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_declaration([NotNull] LentoParser.Function_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.variable_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_declaration([NotNull] LentoParser.Variable_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.variable_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_assignment([NotNull] LentoParser.Variable_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.variable_initialization"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_initialization([NotNull] LentoParser.Variable_initializationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.expression_separator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_separator([NotNull] LentoParser.Expression_separatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] LentoParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="LentoParser.compilation_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompilation_unit([NotNull] LentoParser.Compilation_unitContext context);
}
} // namespace LentoCore.Parser
