//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Grammar\LentoLexer.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace LentoCore.Parser {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class LentoLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		SP=1, NL=2, COMMENT_SINGLE=3, COMMENT_MULTI=4, INTEGER=5, FLOATING_POINT=6, 
		NUMBER_HEX=7, NUMBER_BINARY=8, IDENTIFIER=9, IDENTIFIER_NAMESPACED=10, 
		IDENTIFIER_IGNORE=11, ATOM=12, ESCAPED=13, SPRING=14, CHARACTER=15, LPAREN=16, 
		RPAREN=17, LBRACKET=18, RBRACKET=19, LBRACE=20, RBRACE=21, ASSIGN=22, 
		SEPARATOR_COMMA=23, SEPARATOR_DOT=24, COLON=25, SEMI_COLON=26, OPERATOR=27;
	public const int
		COMMENTS=2;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN", "COMMENTS"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"SP", "NL", "COMMENT_SINGLE", "COMMENT_MULTI", "LETTER", "DIGIT", "DIGIT_HEX", 
		"DIGIT_BINARY", "DECIMAL_POINT", "NUMBER_PREFIX_HEX", "NUMBER_PREFIX_BINARY", 
		"INTEGER", "FLOATING_POINT", "NUMBER_HEX", "NUMBER_BINARY", "IDENTIFIER", 
		"IDENTIFIER_NAMESPACED", "IDENTIFIER_IGNORE", "ATOM", "ESCAPED", "SPRING", 
		"CHARACTER", "LPAREN", "RPAREN", "LBRACKET", "RBRACKET", "LBRACE", "RBRACE", 
		"ASSIGN", "SEPARATOR_COMMA", "SEPARATOR_DOT", "COLON", "SEMI_COLON", "OPERATOR"
	};


	public LentoLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public LentoLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, "'('", "')'", "'['", "']'", "'{'", "'}'", "'='", 
		"','", "'.'", "':'", "';'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "SP", "NL", "COMMENT_SINGLE", "COMMENT_MULTI", "INTEGER", "FLOATING_POINT", 
		"NUMBER_HEX", "NUMBER_BINARY", "IDENTIFIER", "IDENTIFIER_NAMESPACED", 
		"IDENTIFIER_IGNORE", "ATOM", "ESCAPED", "SPRING", "CHARACTER", "LPAREN", 
		"RPAREN", "LBRACKET", "RBRACKET", "LBRACE", "RBRACE", "ASSIGN", "SEPARATOR_COMMA", 
		"SEPARATOR_DOT", "COLON", "SEMI_COLON", "OPERATOR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "LentoLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static LentoLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1D', '\xFB', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x3', '\x2', '\x6', '\x2', 'I', '\n', '\x2', '\r', '\x2', 
		'\xE', '\x2', 'J', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x6', '\x3', 
		'P', '\n', '\x3', '\r', '\x3', '\xE', '\x3', 'Q', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\a', '\x4', 'X', '\n', '\x4', '\f', 
		'\x4', '\xE', '\x4', '[', '\v', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\a', '\x5', '\x63', 
		'\n', '\x5', '\f', '\x5', '\xE', '\x5', '\x66', '\v', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', 
		'\x5', '\x6', 'n', '\n', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x5', '\b', 't', '\n', '\b', '\x3', '\t', '\x3', '\t', '\x3', 
		'\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\r', '\x6', '\r', '\x81', '\n', '\r', 
		'\r', '\r', '\xE', '\r', '\x82', '\x3', '\xE', '\x5', '\xE', '\x86', '\n', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x6', '\xE', '\x8A', '\n', '\xE', 
		'\r', '\xE', '\xE', '\xE', '\x8B', '\x3', '\xF', '\x3', '\xF', '\x6', 
		'\xF', '\x90', '\n', '\xF', '\r', '\xF', '\xE', '\xF', '\x91', '\x3', 
		'\x10', '\x3', '\x10', '\x6', '\x10', '\x96', '\n', '\x10', '\r', '\x10', 
		'\xE', '\x10', '\x97', '\x3', '\x11', '\x6', '\x11', '\x9B', '\n', '\x11', 
		'\r', '\x11', '\xE', '\x11', '\x9C', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\a', '\x11', '\xA2', '\n', '\x11', '\f', '\x11', '\xE', '\x11', 
		'\xA5', '\v', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x6', '\x12', '\xAB', '\n', '\x12', '\r', '\x12', '\xE', '\x12', 
		'\xAC', '\x3', '\x13', '\x3', '\x13', '\a', '\x13', '\xB1', '\n', '\x13', 
		'\f', '\x13', '\xE', '\x13', '\xB4', '\v', '\x13', '\x3', '\x13', '\x5', 
		'\x13', '\xB7', '\n', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x15', '\x5', '\x15', '\xCC', '\n', '\x15', '\x3', '\x16', '\x3', 
		'\x16', '\x3', '\x16', '\a', '\x16', '\xD1', '\n', '\x16', '\f', '\x16', 
		'\xE', '\x16', '\xD4', '\v', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', 
		'\x17', '\x3', '\x17', '\x3', '\x17', '\x5', '\x17', '\xDB', '\n', '\x17', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', 
		'\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', 
		'\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', 
		'\x3', '\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x3', ' ', '\x3', ' ', '\x3', 
		'!', '\x3', '!', '\x3', '\"', '\x3', '\"', '\x3', '#', '\x3', '#', '\x3', 
		'#', '\x6', '#', '\xF8', '\n', '#', '\r', '#', '\xE', '#', '\xF9', '\x3', 
		'\x64', '\x2', '$', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', 
		'\v', '\x2', '\r', '\x2', '\xF', '\x2', '\x11', '\x2', '\x13', '\x2', 
		'\x15', '\x2', '\x17', '\x2', '\x19', '\a', '\x1B', '\b', '\x1D', '\t', 
		'\x1F', '\n', '!', '\v', '#', '\f', '%', '\r', '\'', '\xE', ')', '\xF', 
		'+', '\x10', '-', '\x11', '/', '\x12', '\x31', '\x13', '\x33', '\x14', 
		'\x35', '\x15', '\x37', '\x16', '\x39', '\x17', ';', '\x18', '=', '\x19', 
		'?', '\x1A', '\x41', '\x1B', '\x43', '\x1C', '\x45', '\x1D', '\x3', '\x2', 
		'\n', '\x4', '\x2', '\v', '\v', '\"', '\"', '\x4', '\x2', '\f', '\f', 
		'\xF', '\xF', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x3', '\x2', '\x32', 
		';', '\x4', '\x2', '\x43', 'H', '\x63', 'h', '\x3', '\x2', '$', '$', '\x3', 
		'\x2', ')', ')', '\f', '\x2', '#', '#', '%', '(', ',', '-', '/', '/', 
		'\x31', '\x31', '>', '>', '@', '\x42', '`', '`', '~', '~', '\x80', '\x80', 
		'\x2', '\x10F', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', 
		'\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', '\x39', '\x3', 
		'\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', '\x2', '=', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '?', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x41', '\x3', '\x2', '\x2', '\x2', '\x2', '\x43', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x45', '\x3', '\x2', '\x2', '\x2', '\x3', 'H', '\x3', '\x2', 
		'\x2', '\x2', '\x5', 'O', '\x3', '\x2', '\x2', '\x2', '\a', 'S', '\x3', 
		'\x2', '\x2', '\x2', '\t', '^', '\x3', '\x2', '\x2', '\x2', '\v', 'm', 
		'\x3', '\x2', '\x2', '\x2', '\r', 'o', '\x3', '\x2', '\x2', '\x2', '\xF', 
		's', '\x3', '\x2', '\x2', '\x2', '\x11', 'u', '\x3', '\x2', '\x2', '\x2', 
		'\x13', 'w', '\x3', '\x2', '\x2', '\x2', '\x15', 'y', '\x3', '\x2', '\x2', 
		'\x2', '\x17', '|', '\x3', '\x2', '\x2', '\x2', '\x19', '\x80', '\x3', 
		'\x2', '\x2', '\x2', '\x1B', '\x85', '\x3', '\x2', '\x2', '\x2', '\x1D', 
		'\x8D', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x93', '\x3', '\x2', '\x2', 
		'\x2', '!', '\x9A', '\x3', '\x2', '\x2', '\x2', '#', '\xA6', '\x3', '\x2', 
		'\x2', '\x2', '%', '\xAE', '\x3', '\x2', '\x2', '\x2', '\'', '\xB8', '\x3', 
		'\x2', '\x2', '\x2', ')', '\xCB', '\x3', '\x2', '\x2', '\x2', '+', '\xCD', 
		'\x3', '\x2', '\x2', '\x2', '-', '\xD7', '\x3', '\x2', '\x2', '\x2', '/', 
		'\xDE', '\x3', '\x2', '\x2', '\x2', '\x31', '\xE0', '\x3', '\x2', '\x2', 
		'\x2', '\x33', '\xE2', '\x3', '\x2', '\x2', '\x2', '\x35', '\xE4', '\x3', 
		'\x2', '\x2', '\x2', '\x37', '\xE6', '\x3', '\x2', '\x2', '\x2', '\x39', 
		'\xE8', '\x3', '\x2', '\x2', '\x2', ';', '\xEA', '\x3', '\x2', '\x2', 
		'\x2', '=', '\xEC', '\x3', '\x2', '\x2', '\x2', '?', '\xEE', '\x3', '\x2', 
		'\x2', '\x2', '\x41', '\xF0', '\x3', '\x2', '\x2', '\x2', '\x43', '\xF2', 
		'\x3', '\x2', '\x2', '\x2', '\x45', '\xF7', '\x3', '\x2', '\x2', '\x2', 
		'G', 'I', '\t', '\x2', '\x2', '\x2', 'H', 'G', '\x3', '\x2', '\x2', '\x2', 
		'I', 'J', '\x3', '\x2', '\x2', '\x2', 'J', 'H', '\x3', '\x2', '\x2', '\x2', 
		'J', 'K', '\x3', '\x2', '\x2', '\x2', 'K', '\x4', '\x3', '\x2', '\x2', 
		'\x2', 'L', 'P', '\t', '\x3', '\x2', '\x2', 'M', 'N', '\a', '\xF', '\x2', 
		'\x2', 'N', 'P', '\a', '\f', '\x2', '\x2', 'O', 'L', '\x3', '\x2', '\x2', 
		'\x2', 'O', 'M', '\x3', '\x2', '\x2', '\x2', 'P', 'Q', '\x3', '\x2', '\x2', 
		'\x2', 'Q', 'O', '\x3', '\x2', '\x2', '\x2', 'Q', 'R', '\x3', '\x2', '\x2', 
		'\x2', 'R', '\x6', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\a', '\x31', 
		'\x2', '\x2', 'T', 'U', '\a', '\x31', '\x2', '\x2', 'U', 'Y', '\x3', '\x2', 
		'\x2', '\x2', 'V', 'X', '\n', '\x3', '\x2', '\x2', 'W', 'V', '\x3', '\x2', 
		'\x2', '\x2', 'X', '[', '\x3', '\x2', '\x2', '\x2', 'Y', 'W', '\x3', '\x2', 
		'\x2', '\x2', 'Y', 'Z', '\x3', '\x2', '\x2', '\x2', 'Z', '\\', '\x3', 
		'\x2', '\x2', '\x2', '[', 'Y', '\x3', '\x2', '\x2', '\x2', '\\', ']', 
		'\b', '\x4', '\x2', '\x2', ']', '\b', '\x3', '\x2', '\x2', '\x2', '^', 
		'_', '\a', '\x31', '\x2', '\x2', '_', '`', '\a', ',', '\x2', '\x2', '`', 
		'\x64', '\x3', '\x2', '\x2', '\x2', '\x61', '\x63', '\v', '\x2', '\x2', 
		'\x2', '\x62', '\x61', '\x3', '\x2', '\x2', '\x2', '\x63', '\x66', '\x3', 
		'\x2', '\x2', '\x2', '\x64', '\x65', '\x3', '\x2', '\x2', '\x2', '\x64', 
		'\x62', '\x3', '\x2', '\x2', '\x2', '\x65', 'g', '\x3', '\x2', '\x2', 
		'\x2', '\x66', '\x64', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\a', ',', 
		'\x2', '\x2', 'h', 'i', '\a', '\x31', '\x2', '\x2', 'i', 'j', '\x3', '\x2', 
		'\x2', '\x2', 'j', 'k', '\b', '\x5', '\x2', '\x2', 'k', '\n', '\x3', '\x2', 
		'\x2', '\x2', 'l', 'n', '\t', '\x4', '\x2', '\x2', 'm', 'l', '\x3', '\x2', 
		'\x2', '\x2', 'n', '\f', '\x3', '\x2', '\x2', '\x2', 'o', 'p', '\t', '\x5', 
		'\x2', '\x2', 'p', '\xE', '\x3', '\x2', '\x2', '\x2', 'q', 't', '\x5', 
		'\r', '\a', '\x2', 'r', 't', '\t', '\x6', '\x2', '\x2', 's', 'q', '\x3', 
		'\x2', '\x2', '\x2', 's', 'r', '\x3', '\x2', '\x2', '\x2', 't', '\x10', 
		'\x3', '\x2', '\x2', '\x2', 'u', 'v', '\x4', '\x32', '\x33', '\x2', 'v', 
		'\x12', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\a', '\x30', '\x2', '\x2', 
		'x', '\x14', '\x3', '\x2', '\x2', '\x2', 'y', 'z', '\a', '\x32', '\x2', 
		'\x2', 'z', '{', '\a', 'z', '\x2', '\x2', '{', '\x16', '\x3', '\x2', '\x2', 
		'\x2', '|', '}', '\a', '\x32', '\x2', '\x2', '}', '~', '\a', '\x64', '\x2', 
		'\x2', '~', '\x18', '\x3', '\x2', '\x2', '\x2', '\x7F', '\x81', '\x5', 
		'\r', '\a', '\x2', '\x80', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x81', 
		'\x82', '\x3', '\x2', '\x2', '\x2', '\x82', '\x80', '\x3', '\x2', '\x2', 
		'\x2', '\x82', '\x83', '\x3', '\x2', '\x2', '\x2', '\x83', '\x1A', '\x3', 
		'\x2', '\x2', '\x2', '\x84', '\x86', '\x5', '\x19', '\r', '\x2', '\x85', 
		'\x84', '\x3', '\x2', '\x2', '\x2', '\x85', '\x86', '\x3', '\x2', '\x2', 
		'\x2', '\x86', '\x87', '\x3', '\x2', '\x2', '\x2', '\x87', '\x89', '\x5', 
		'\x13', '\n', '\x2', '\x88', '\x8A', '\x5', '\r', '\a', '\x2', '\x89', 
		'\x88', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\x3', '\x2', '\x2', 
		'\x2', '\x8B', '\x89', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8C', '\x3', 
		'\x2', '\x2', '\x2', '\x8C', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x8D', 
		'\x8F', '\x5', '\x15', '\v', '\x2', '\x8E', '\x90', '\x5', '\xF', '\b', 
		'\x2', '\x8F', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x90', '\x91', '\x3', 
		'\x2', '\x2', '\x2', '\x91', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x91', 
		'\x92', '\x3', '\x2', '\x2', '\x2', '\x92', '\x1E', '\x3', '\x2', '\x2', 
		'\x2', '\x93', '\x95', '\x5', '\x17', '\f', '\x2', '\x94', '\x96', '\x5', 
		'\x11', '\t', '\x2', '\x95', '\x94', '\x3', '\x2', '\x2', '\x2', '\x96', 
		'\x97', '\x3', '\x2', '\x2', '\x2', '\x97', '\x95', '\x3', '\x2', '\x2', 
		'\x2', '\x97', '\x98', '\x3', '\x2', '\x2', '\x2', '\x98', ' ', '\x3', 
		'\x2', '\x2', '\x2', '\x99', '\x9B', '\x5', '\v', '\x6', '\x2', '\x9A', 
		'\x99', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', '\x3', '\x2', '\x2', 
		'\x2', '\x9C', '\x9A', '\x3', '\x2', '\x2', '\x2', '\x9C', '\x9D', '\x3', 
		'\x2', '\x2', '\x2', '\x9D', '\xA3', '\x3', '\x2', '\x2', '\x2', '\x9E', 
		'\xA2', '\x5', '\r', '\a', '\x2', '\x9F', '\xA2', '\x5', '\v', '\x6', 
		'\x2', '\xA0', '\xA2', '\a', '\x61', '\x2', '\x2', '\xA1', '\x9E', '\x3', 
		'\x2', '\x2', '\x2', '\xA1', '\x9F', '\x3', '\x2', '\x2', '\x2', '\xA1', 
		'\xA0', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA5', '\x3', '\x2', '\x2', 
		'\x2', '\xA3', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA4', '\x3', 
		'\x2', '\x2', '\x2', '\xA4', '\"', '\x3', '\x2', '\x2', '\x2', '\xA5', 
		'\xA3', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xAA', '\x5', '!', '\x11', 
		'\x2', '\xA7', '\xA8', '\x5', '?', ' ', '\x2', '\xA8', '\xA9', '\x5', 
		'!', '\x11', '\x2', '\xA9', '\xAB', '\x3', '\x2', '\x2', '\x2', '\xAA', 
		'\xA7', '\x3', '\x2', '\x2', '\x2', '\xAB', '\xAC', '\x3', '\x2', '\x2', 
		'\x2', '\xAC', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAD', '\x3', 
		'\x2', '\x2', '\x2', '\xAD', '$', '\x3', '\x2', '\x2', '\x2', '\xAE', 
		'\xB2', '\a', '\x61', '\x2', '\x2', '\xAF', '\xB1', '\x5', '\r', '\a', 
		'\x2', '\xB0', '\xAF', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xB4', '\x3', 
		'\x2', '\x2', '\x2', '\xB2', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xB2', 
		'\xB3', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB6', '\x3', '\x2', '\x2', 
		'\x2', '\xB4', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB7', '\x5', 
		'!', '\x11', '\x2', '\xB6', '\xB5', '\x3', '\x2', '\x2', '\x2', '\xB6', 
		'\xB7', '\x3', '\x2', '\x2', '\x2', '\xB7', '&', '\x3', '\x2', '\x2', 
		'\x2', '\xB8', '\xB9', '\a', '<', '\x2', '\x2', '\xB9', '\xBA', '\x5', 
		'!', '\x11', '\x2', '\xBA', '(', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xBC', 
		'\a', '^', '\x2', '\x2', '\xBC', '\xBD', '\a', 'w', '\x2', '\x2', '\xBD', 
		'\xBE', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xBF', '\x5', '\xF', '\b', 
		'\x2', '\xBF', '\xC0', '\x5', '\xF', '\b', '\x2', '\xC0', '\xC1', '\x5', 
		'\xF', '\b', '\x2', '\xC1', '\xC2', '\x5', '\xF', '\b', '\x2', '\xC2', 
		'\xCC', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xC4', '\a', '^', '\x2', 
		'\x2', '\xC4', '\xCC', '\a', '$', '\x2', '\x2', '\xC5', '\xC6', '\a', 
		'^', '\x2', '\x2', '\xC6', '\xCC', '\a', ')', '\x2', '\x2', '\xC7', '\xC8', 
		'\a', '^', '\x2', '\x2', '\xC8', '\xCC', '\a', '^', '\x2', '\x2', '\xC9', 
		'\xCA', '\a', '^', '\x2', '\x2', '\xCA', '\xCC', '\v', '\x2', '\x2', '\x2', 
		'\xCB', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xCB', '\xC3', '\x3', '\x2', 
		'\x2', '\x2', '\xCB', '\xC5', '\x3', '\x2', '\x2', '\x2', '\xCB', '\xC7', 
		'\x3', '\x2', '\x2', '\x2', '\xCB', '\xC9', '\x3', '\x2', '\x2', '\x2', 
		'\xCC', '*', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xD2', '\a', '$', '\x2', 
		'\x2', '\xCE', '\xD1', '\x5', ')', '\x15', '\x2', '\xCF', '\xD1', '\n', 
		'\a', '\x2', '\x2', '\xD0', '\xCE', '\x3', '\x2', '\x2', '\x2', '\xD0', 
		'\xCF', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xD4', '\x3', '\x2', '\x2', 
		'\x2', '\xD2', '\xD0', '\x3', '\x2', '\x2', '\x2', '\xD2', '\xD3', '\x3', 
		'\x2', '\x2', '\x2', '\xD3', '\xD5', '\x3', '\x2', '\x2', '\x2', '\xD4', 
		'\xD2', '\x3', '\x2', '\x2', '\x2', '\xD5', '\xD6', '\a', '$', '\x2', 
		'\x2', '\xD6', ',', '\x3', '\x2', '\x2', '\x2', '\xD7', '\xDA', '\a', 
		')', '\x2', '\x2', '\xD8', '\xDB', '\x5', ')', '\x15', '\x2', '\xD9', 
		'\xDB', '\n', '\b', '\x2', '\x2', '\xDA', '\xD8', '\x3', '\x2', '\x2', 
		'\x2', '\xDA', '\xD9', '\x3', '\x2', '\x2', '\x2', '\xDB', '\xDC', '\x3', 
		'\x2', '\x2', '\x2', '\xDC', '\xDD', '\a', ')', '\x2', '\x2', '\xDD', 
		'.', '\x3', '\x2', '\x2', '\x2', '\xDE', '\xDF', '\a', '*', '\x2', '\x2', 
		'\xDF', '\x30', '\x3', '\x2', '\x2', '\x2', '\xE0', '\xE1', '\a', '+', 
		'\x2', '\x2', '\xE1', '\x32', '\x3', '\x2', '\x2', '\x2', '\xE2', '\xE3', 
		'\a', ']', '\x2', '\x2', '\xE3', '\x34', '\x3', '\x2', '\x2', '\x2', '\xE4', 
		'\xE5', '\a', '_', '\x2', '\x2', '\xE5', '\x36', '\x3', '\x2', '\x2', 
		'\x2', '\xE6', '\xE7', '\a', '}', '\x2', '\x2', '\xE7', '\x38', '\x3', 
		'\x2', '\x2', '\x2', '\xE8', '\xE9', '\a', '\x7F', '\x2', '\x2', '\xE9', 
		':', '\x3', '\x2', '\x2', '\x2', '\xEA', '\xEB', '\a', '?', '\x2', '\x2', 
		'\xEB', '<', '\x3', '\x2', '\x2', '\x2', '\xEC', '\xED', '\a', '.', '\x2', 
		'\x2', '\xED', '>', '\x3', '\x2', '\x2', '\x2', '\xEE', '\xEF', '\a', 
		'\x30', '\x2', '\x2', '\xEF', '@', '\x3', '\x2', '\x2', '\x2', '\xF0', 
		'\xF1', '\a', '<', '\x2', '\x2', '\xF1', '\x42', '\x3', '\x2', '\x2', 
		'\x2', '\xF2', '\xF3', '\a', '=', '\x2', '\x2', '\xF3', '\x44', '\x3', 
		'\x2', '\x2', '\x2', '\xF4', '\xF8', '\x5', ';', '\x1E', '\x2', '\xF5', 
		'\xF8', '\x5', '\x41', '!', '\x2', '\xF6', '\xF8', '\t', '\t', '\x2', 
		'\x2', '\xF7', '\xF4', '\x3', '\x2', '\x2', '\x2', '\xF7', '\xF5', '\x3', 
		'\x2', '\x2', '\x2', '\xF7', '\xF6', '\x3', '\x2', '\x2', '\x2', '\xF8', 
		'\xF9', '\x3', '\x2', '\x2', '\x2', '\xF9', '\xF7', '\x3', '\x2', '\x2', 
		'\x2', '\xF9', '\xFA', '\x3', '\x2', '\x2', '\x2', '\xFA', '\x46', '\x3', 
		'\x2', '\x2', '\x2', '\x1B', '\x2', 'J', 'O', 'Q', 'Y', '\x64', 'm', 's', 
		'\x82', '\x85', '\x8B', '\x91', '\x97', '\x9C', '\xA1', '\xA3', '\xAC', 
		'\xB2', '\xB6', '\xCB', '\xD0', '\xD2', '\xDA', '\xF7', '\xF9', '\x3', 
		'\x2', '\x4', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace LentoCore.Parser
