//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Grammar\LentoLexer.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace LentoCore.Parser {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class LentoLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		SP=1, NL=2, COMMENT_SINGLE=3, COMMENT_MULTI=4, INTEGER=5, FLOATING_POINT=6, 
		NUMBER_HEX=7, NUMBER_BINARY=8, IDENTIFIER_SPECIAL=9, IDENTIFIER=10, IGNORE_IDENTIFIER=11, 
		ATOM=12, FUNCTION_NAME=13, TYPE=14, SPRING=15, CHARACTER=16, LPAREN=17, 
		RPAREN=18, LBRACKET=19, RBRACKET=20, LBRACE=21, RBRACE=22, ASSIGN=23, 
		SEPARATOR_COMMA=24, COLON=25, SEMI_COLON=26, OPERATOR=27;
	public const int
		COMMENTS=2;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN", "COMMENTS"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"SP", "NL", "COMMENT_SINGLE", "COMMENT_MULTI", "LETTER", "DIGIT", "DIGIT_HEX", 
		"DIGIT_BINARY", "DECIMAL_POINT", "NUMBER_PREFIX_HEX", "NUMBER_PREFIX_BINARY", 
		"INTEGER", "FLOATING_POINT", "NUMBER_HEX", "NUMBER_BINARY", "IDENTIFIER_SPECIAL", 
		"IDENTIFIER", "IGNORE_IDENTIFIER", "ATOM", "FUNCTION_NAME", "TYPE", "SPRING", 
		"CHARACTER", "LPAREN", "RPAREN", "LBRACKET", "RBRACKET", "LBRACE", "RBRACE", 
		"ASSIGN", "SEPARATOR_COMMA", "COLON", "SEMI_COLON", "OPERATOR_ALLOWED", 
		"OPERATOR"
	};


	public LentoLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public LentoLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, "'('", "')'", "'['", "']'", "'{'", "'}'", 
		"'='", "','", "':'", "';'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "SP", "NL", "COMMENT_SINGLE", "COMMENT_MULTI", "INTEGER", "FLOATING_POINT", 
		"NUMBER_HEX", "NUMBER_BINARY", "IDENTIFIER_SPECIAL", "IDENTIFIER", "IGNORE_IDENTIFIER", 
		"ATOM", "FUNCTION_NAME", "TYPE", "SPRING", "CHARACTER", "LPAREN", "RPAREN", 
		"LBRACKET", "RBRACKET", "LBRACE", "RBRACE", "ASSIGN", "SEPARATOR_COMMA", 
		"COLON", "SEMI_COLON", "OPERATOR"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "LentoLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static LentoLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1D', '\xFF', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x3', '\x2', '\x6', '\x2', 'K', 
		'\n', '\x2', '\r', '\x2', '\xE', '\x2', 'L', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x6', '\x3', 'R', '\n', '\x3', '\r', '\x3', '\xE', '\x3', 
		'S', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\a', '\x4', 
		'Z', '\n', '\x4', '\f', '\x4', '\xE', '\x4', ']', '\v', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\a', '\x5', '\x65', '\n', '\x5', '\f', '\x5', '\xE', '\x5', 'h', 
		'\v', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x5', '\x6', 'p', '\n', '\x6', '\x3', '\a', '\x3', 
		'\a', '\x3', '\b', '\x3', '\b', '\x5', '\b', 'v', '\n', '\b', '\x3', '\t', 
		'\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x6', '\r', 
		'\x83', '\n', '\r', '\r', '\r', '\xE', '\r', '\x84', '\x3', '\xE', '\x5', 
		'\xE', '\x88', '\n', '\xE', '\x3', '\xE', '\x3', '\xE', '\x6', '\xE', 
		'\x8C', '\n', '\xE', '\r', '\xE', '\xE', '\xE', '\x8D', '\x3', '\xF', 
		'\x3', '\xF', '\x6', '\xF', '\x92', '\n', '\xF', '\r', '\xF', '\xE', '\xF', 
		'\x93', '\x3', '\x10', '\x3', '\x10', '\x6', '\x10', '\x98', '\n', '\x10', 
		'\r', '\x10', '\xE', '\x10', '\x99', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x12', '\x3', '\x12', '\x6', '\x12', '\xA0', '\n', '\x12', '\r', '\x12', 
		'\xE', '\x12', '\xA1', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\a', '\x12', '\xA8', '\n', '\x12', '\f', '\x12', '\xE', '\x12', 
		'\xAB', '\v', '\x12', '\x3', '\x13', '\x3', '\x13', '\a', '\x13', '\xAF', 
		'\n', '\x13', '\f', '\x13', '\xE', '\x13', '\xB2', '\v', '\x13', '\x3', 
		'\x13', '\x5', '\x13', '\xB5', '\n', '\x13', '\x3', '\x14', '\x3', '\x14', 
		'\x6', '\x14', '\xB9', '\n', '\x14', '\r', '\x14', '\xE', '\x14', '\xBA', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x16', '\x6', '\x16', '\xC0', '\n', 
		'\x16', '\r', '\x16', '\xE', '\x16', '\xC1', '\x3', '\x16', '\x3', '\x16', 
		'\x3', '\x16', '\a', '\x16', '\xC7', '\n', '\x16', '\f', '\x16', '\xE', 
		'\x16', '\xCA', '\v', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', 
		'\x3', '\x17', '\a', '\x17', '\xD0', '\n', '\x17', '\f', '\x17', '\xE', 
		'\x17', '\xD3', '\v', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x18', 
		'\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x6', '\x18', '\xDB', '\n', 
		'\x18', '\r', '\x18', '\xE', '\x18', '\xDC', '\x3', '\x18', '\x3', '\x18', 
		'\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', 
		'\x3', '\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', '\x1D', 
		'\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x3', ' ', 
		'\x3', ' ', '\x3', '!', '\x3', '!', '\x3', '\"', '\x3', '\"', '\x3', '#', 
		'\x3', '#', '\x3', '#', '\x3', '#', '\x5', '#', '\xF9', '\n', '#', '\x3', 
		'$', '\x6', '$', '\xFC', '\n', '$', '\r', '$', '\xE', '$', '\xFD', '\x3', 
		'\x66', '\x2', '%', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', 
		'\v', '\x2', '\r', '\x2', '\xF', '\x2', '\x11', '\x2', '\x13', '\x2', 
		'\x15', '\x2', '\x17', '\x2', '\x19', '\a', '\x1B', '\b', '\x1D', '\t', 
		'\x1F', '\n', '!', '\v', '#', '\f', '%', '\r', '\'', '\xE', ')', '\xF', 
		'+', '\x10', '-', '\x11', '/', '\x12', '\x31', '\x13', '\x33', '\x14', 
		'\x35', '\x15', '\x37', '\x16', '\x39', '\x17', ';', '\x18', '=', '\x19', 
		'?', '\x1A', '\x41', '\x1B', '\x43', '\x1C', '\x45', '\x2', 'G', '\x1D', 
		'\x3', '\x2', '\n', '\x4', '\x2', '\v', '\v', '\"', '\"', '\x4', '\x2', 
		'\f', '\f', '\xF', '\xF', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x3', 
		'\x2', '\x32', ';', '\x4', '\x2', '\x43', 'H', '\x63', 'h', '\x3', '\x2', 
		'$', '$', '\x3', '\x2', ')', ')', '\r', '\x2', '#', '#', '%', '%', '\'', 
		'(', ',', '-', '/', '/', '\x31', '\x31', '>', '>', '@', '\x42', '`', '`', 
		'~', '~', '\x80', '\x80', '\x2', '\x116', '\x2', '\x3', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', 
		'\x3', '\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'+', '\x3', '\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '/', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x35', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x37', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x39', '\x3', '\x2', '\x2', '\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '=', '\x3', '\x2', '\x2', '\x2', '\x2', '?', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x41', '\x3', '\x2', '\x2', '\x2', '\x2', '\x43', '\x3', 
		'\x2', '\x2', '\x2', '\x2', 'G', '\x3', '\x2', '\x2', '\x2', '\x3', 'J', 
		'\x3', '\x2', '\x2', '\x2', '\x5', 'Q', '\x3', '\x2', '\x2', '\x2', '\a', 
		'U', '\x3', '\x2', '\x2', '\x2', '\t', '`', '\x3', '\x2', '\x2', '\x2', 
		'\v', 'o', '\x3', '\x2', '\x2', '\x2', '\r', 'q', '\x3', '\x2', '\x2', 
		'\x2', '\xF', 'u', '\x3', '\x2', '\x2', '\x2', '\x11', 'w', '\x3', '\x2', 
		'\x2', '\x2', '\x13', 'y', '\x3', '\x2', '\x2', '\x2', '\x15', '{', '\x3', 
		'\x2', '\x2', '\x2', '\x17', '~', '\x3', '\x2', '\x2', '\x2', '\x19', 
		'\x82', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x87', '\x3', '\x2', '\x2', 
		'\x2', '\x1D', '\x8F', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x95', '\x3', 
		'\x2', '\x2', '\x2', '!', '\x9B', '\x3', '\x2', '\x2', '\x2', '#', '\x9F', 
		'\x3', '\x2', '\x2', '\x2', '%', '\xAC', '\x3', '\x2', '\x2', '\x2', '\'', 
		'\xB6', '\x3', '\x2', '\x2', '\x2', ')', '\xBC', '\x3', '\x2', '\x2', 
		'\x2', '+', '\xBF', '\x3', '\x2', '\x2', '\x2', '-', '\xCB', '\x3', '\x2', 
		'\x2', '\x2', '/', '\xD6', '\x3', '\x2', '\x2', '\x2', '\x31', '\xE0', 
		'\x3', '\x2', '\x2', '\x2', '\x33', '\xE2', '\x3', '\x2', '\x2', '\x2', 
		'\x35', '\xE4', '\x3', '\x2', '\x2', '\x2', '\x37', '\xE6', '\x3', '\x2', 
		'\x2', '\x2', '\x39', '\xE8', '\x3', '\x2', '\x2', '\x2', ';', '\xEA', 
		'\x3', '\x2', '\x2', '\x2', '=', '\xEC', '\x3', '\x2', '\x2', '\x2', '?', 
		'\xEE', '\x3', '\x2', '\x2', '\x2', '\x41', '\xF0', '\x3', '\x2', '\x2', 
		'\x2', '\x43', '\xF2', '\x3', '\x2', '\x2', '\x2', '\x45', '\xF8', '\x3', 
		'\x2', '\x2', '\x2', 'G', '\xFB', '\x3', '\x2', '\x2', '\x2', 'I', 'K', 
		'\t', '\x2', '\x2', '\x2', 'J', 'I', '\x3', '\x2', '\x2', '\x2', 'K', 
		'L', '\x3', '\x2', '\x2', '\x2', 'L', 'J', '\x3', '\x2', '\x2', '\x2', 
		'L', 'M', '\x3', '\x2', '\x2', '\x2', 'M', '\x4', '\x3', '\x2', '\x2', 
		'\x2', 'N', 'R', '\t', '\x3', '\x2', '\x2', 'O', 'P', '\a', '\xF', '\x2', 
		'\x2', 'P', 'R', '\a', '\f', '\x2', '\x2', 'Q', 'N', '\x3', '\x2', '\x2', 
		'\x2', 'Q', 'O', '\x3', '\x2', '\x2', '\x2', 'R', 'S', '\x3', '\x2', '\x2', 
		'\x2', 'S', 'Q', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\x3', '\x2', '\x2', 
		'\x2', 'T', '\x6', '\x3', '\x2', '\x2', '\x2', 'U', 'V', '\a', '\x31', 
		'\x2', '\x2', 'V', 'W', '\a', '\x31', '\x2', '\x2', 'W', '[', '\x3', '\x2', 
		'\x2', '\x2', 'X', 'Z', '\n', '\x3', '\x2', '\x2', 'Y', 'X', '\x3', '\x2', 
		'\x2', '\x2', 'Z', ']', '\x3', '\x2', '\x2', '\x2', '[', 'Y', '\x3', '\x2', 
		'\x2', '\x2', '[', '\\', '\x3', '\x2', '\x2', '\x2', '\\', '^', '\x3', 
		'\x2', '\x2', '\x2', ']', '[', '\x3', '\x2', '\x2', '\x2', '^', '_', '\b', 
		'\x4', '\x2', '\x2', '_', '\b', '\x3', '\x2', '\x2', '\x2', '`', '\x61', 
		'\a', '\x31', '\x2', '\x2', '\x61', '\x62', '\a', ',', '\x2', '\x2', '\x62', 
		'\x66', '\x3', '\x2', '\x2', '\x2', '\x63', '\x65', '\v', '\x2', '\x2', 
		'\x2', '\x64', '\x63', '\x3', '\x2', '\x2', '\x2', '\x65', 'h', '\x3', 
		'\x2', '\x2', '\x2', '\x66', 'g', '\x3', '\x2', '\x2', '\x2', '\x66', 
		'\x64', '\x3', '\x2', '\x2', '\x2', 'g', 'i', '\x3', '\x2', '\x2', '\x2', 
		'h', '\x66', '\x3', '\x2', '\x2', '\x2', 'i', 'j', '\a', ',', '\x2', '\x2', 
		'j', 'k', '\a', '\x31', '\x2', '\x2', 'k', 'l', '\x3', '\x2', '\x2', '\x2', 
		'l', 'm', '\b', '\x5', '\x2', '\x2', 'm', '\n', '\x3', '\x2', '\x2', '\x2', 
		'n', 'p', '\t', '\x4', '\x2', '\x2', 'o', 'n', '\x3', '\x2', '\x2', '\x2', 
		'p', '\f', '\x3', '\x2', '\x2', '\x2', 'q', 'r', '\t', '\x5', '\x2', '\x2', 
		'r', '\xE', '\x3', '\x2', '\x2', '\x2', 's', 'v', '\x5', '\r', '\a', '\x2', 
		't', 'v', '\t', '\x6', '\x2', '\x2', 'u', 's', '\x3', '\x2', '\x2', '\x2', 
		'u', 't', '\x3', '\x2', '\x2', '\x2', 'v', '\x10', '\x3', '\x2', '\x2', 
		'\x2', 'w', 'x', '\x4', '\x32', '\x33', '\x2', 'x', '\x12', '\x3', '\x2', 
		'\x2', '\x2', 'y', 'z', '\a', '\x30', '\x2', '\x2', 'z', '\x14', '\x3', 
		'\x2', '\x2', '\x2', '{', '|', '\a', '\x32', '\x2', '\x2', '|', '}', '\a', 
		'z', '\x2', '\x2', '}', '\x16', '\x3', '\x2', '\x2', '\x2', '~', '\x7F', 
		'\a', '\x32', '\x2', '\x2', '\x7F', '\x80', '\a', '\x64', '\x2', '\x2', 
		'\x80', '\x18', '\x3', '\x2', '\x2', '\x2', '\x81', '\x83', '\x5', '\r', 
		'\a', '\x2', '\x82', '\x81', '\x3', '\x2', '\x2', '\x2', '\x83', '\x84', 
		'\x3', '\x2', '\x2', '\x2', '\x84', '\x82', '\x3', '\x2', '\x2', '\x2', 
		'\x84', '\x85', '\x3', '\x2', '\x2', '\x2', '\x85', '\x1A', '\x3', '\x2', 
		'\x2', '\x2', '\x86', '\x88', '\x5', '\x19', '\r', '\x2', '\x87', '\x86', 
		'\x3', '\x2', '\x2', '\x2', '\x87', '\x88', '\x3', '\x2', '\x2', '\x2', 
		'\x88', '\x89', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8B', '\x5', '\x13', 
		'\n', '\x2', '\x8A', '\x8C', '\x5', '\r', '\a', '\x2', '\x8B', '\x8A', 
		'\x3', '\x2', '\x2', '\x2', '\x8C', '\x8D', '\x3', '\x2', '\x2', '\x2', 
		'\x8D', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8E', '\x3', '\x2', 
		'\x2', '\x2', '\x8E', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x8F', '\x91', 
		'\x5', '\x15', '\v', '\x2', '\x90', '\x92', '\x5', '\xF', '\b', '\x2', 
		'\x91', '\x90', '\x3', '\x2', '\x2', '\x2', '\x92', '\x93', '\x3', '\x2', 
		'\x2', '\x2', '\x93', '\x91', '\x3', '\x2', '\x2', '\x2', '\x93', '\x94', 
		'\x3', '\x2', '\x2', '\x2', '\x94', '\x1E', '\x3', '\x2', '\x2', '\x2', 
		'\x95', '\x97', '\x5', '\x17', '\f', '\x2', '\x96', '\x98', '\x5', '\x11', 
		'\t', '\x2', '\x97', '\x96', '\x3', '\x2', '\x2', '\x2', '\x98', '\x99', 
		'\x3', '\x2', '\x2', '\x2', '\x99', '\x97', '\x3', '\x2', '\x2', '\x2', 
		'\x99', '\x9A', '\x3', '\x2', '\x2', '\x2', '\x9A', ' ', '\x3', '\x2', 
		'\x2', '\x2', '\x9B', '\x9C', '\x4', '%', '(', '\x2', '\x9C', '\"', '\x3', 
		'\x2', '\x2', '\x2', '\x9D', '\xA0', '\x5', '\v', '\x6', '\x2', '\x9E', 
		'\xA0', '\x5', '!', '\x11', '\x2', '\x9F', '\x9D', '\x3', '\x2', '\x2', 
		'\x2', '\x9F', '\x9E', '\x3', '\x2', '\x2', '\x2', '\xA0', '\xA1', '\x3', 
		'\x2', '\x2', '\x2', '\xA1', '\x9F', '\x3', '\x2', '\x2', '\x2', '\xA1', 
		'\xA2', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA9', '\x3', '\x2', '\x2', 
		'\x2', '\xA3', '\xA8', '\x5', '\r', '\a', '\x2', '\xA4', '\xA8', '\x5', 
		'\v', '\x6', '\x2', '\xA5', '\xA8', '\x5', '!', '\x11', '\x2', '\xA6', 
		'\xA8', '\a', '\x61', '\x2', '\x2', '\xA7', '\xA3', '\x3', '\x2', '\x2', 
		'\x2', '\xA7', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xA7', '\xA5', '\x3', 
		'\x2', '\x2', '\x2', '\xA7', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA8', 
		'\xAB', '\x3', '\x2', '\x2', '\x2', '\xA9', '\xA7', '\x3', '\x2', '\x2', 
		'\x2', '\xA9', '\xAA', '\x3', '\x2', '\x2', '\x2', '\xAA', '$', '\x3', 
		'\x2', '\x2', '\x2', '\xAB', '\xA9', '\x3', '\x2', '\x2', '\x2', '\xAC', 
		'\xB0', '\a', '\x61', '\x2', '\x2', '\xAD', '\xAF', '\x5', '\r', '\a', 
		'\x2', '\xAE', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xB2', '\x3', 
		'\x2', '\x2', '\x2', '\xB0', '\xAE', '\x3', '\x2', '\x2', '\x2', '\xB0', 
		'\xB1', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xB4', '\x3', '\x2', '\x2', 
		'\x2', '\xB2', '\xB0', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB5', '\x5', 
		'#', '\x12', '\x2', '\xB4', '\xB3', '\x3', '\x2', '\x2', '\x2', '\xB4', 
		'\xB5', '\x3', '\x2', '\x2', '\x2', '\xB5', '&', '\x3', '\x2', '\x2', 
		'\x2', '\xB6', '\xB8', '\a', '<', '\x2', '\x2', '\xB7', '\xB9', '\x5', 
		'#', '\x12', '\x2', '\xB8', '\xB7', '\x3', '\x2', '\x2', '\x2', '\xB9', 
		'\xBA', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xB8', '\x3', '\x2', '\x2', 
		'\x2', '\xBA', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xBB', '(', '\x3', 
		'\x2', '\x2', '\x2', '\xBC', '\xBD', '\x5', '#', '\x12', '\x2', '\xBD', 
		'*', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xC0', '\x5', '\v', '\x6', '\x2', 
		'\xBF', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xC0', '\xC1', '\x3', '\x2', 
		'\x2', '\x2', '\xC1', '\xBF', '\x3', '\x2', '\x2', '\x2', '\xC1', '\xC2', 
		'\x3', '\x2', '\x2', '\x2', '\xC2', '\xC8', '\x3', '\x2', '\x2', '\x2', 
		'\xC3', '\xC7', '\x5', '\r', '\a', '\x2', '\xC4', '\xC7', '\x5', '\v', 
		'\x6', '\x2', '\xC5', '\xC7', '\a', '\x61', '\x2', '\x2', '\xC6', '\xC3', 
		'\x3', '\x2', '\x2', '\x2', '\xC6', '\xC4', '\x3', '\x2', '\x2', '\x2', 
		'\xC6', '\xC5', '\x3', '\x2', '\x2', '\x2', '\xC7', '\xCA', '\x3', '\x2', 
		'\x2', '\x2', '\xC8', '\xC6', '\x3', '\x2', '\x2', '\x2', '\xC8', '\xC9', 
		'\x3', '\x2', '\x2', '\x2', '\xC9', ',', '\x3', '\x2', '\x2', '\x2', '\xCA', 
		'\xC8', '\x3', '\x2', '\x2', '\x2', '\xCB', '\xD1', '\a', '$', '\x2', 
		'\x2', '\xCC', '\xCD', '\a', '^', '\x2', '\x2', '\xCD', '\xD0', '\a', 
		'$', '\x2', '\x2', '\xCE', '\xD0', '\n', '\a', '\x2', '\x2', '\xCF', '\xCC', 
		'\x3', '\x2', '\x2', '\x2', '\xCF', '\xCE', '\x3', '\x2', '\x2', '\x2', 
		'\xD0', '\xD3', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xCF', '\x3', '\x2', 
		'\x2', '\x2', '\xD1', '\xD2', '\x3', '\x2', '\x2', '\x2', '\xD2', '\xD4', 
		'\x3', '\x2', '\x2', '\x2', '\xD3', '\xD1', '\x3', '\x2', '\x2', '\x2', 
		'\xD4', '\xD5', '\a', '$', '\x2', '\x2', '\xD5', '.', '\x3', '\x2', '\x2', 
		'\x2', '\xD6', '\xDA', '\a', ')', '\x2', '\x2', '\xD7', '\xD8', '\a', 
		'^', '\x2', '\x2', '\xD8', '\xDB', '\a', ')', '\x2', '\x2', '\xD9', '\xDB', 
		'\n', '\b', '\x2', '\x2', '\xDA', '\xD7', '\x3', '\x2', '\x2', '\x2', 
		'\xDA', '\xD9', '\x3', '\x2', '\x2', '\x2', '\xDB', '\xDC', '\x3', '\x2', 
		'\x2', '\x2', '\xDC', '\xDA', '\x3', '\x2', '\x2', '\x2', '\xDC', '\xDD', 
		'\x3', '\x2', '\x2', '\x2', '\xDD', '\xDE', '\x3', '\x2', '\x2', '\x2', 
		'\xDE', '\xDF', '\a', ')', '\x2', '\x2', '\xDF', '\x30', '\x3', '\x2', 
		'\x2', '\x2', '\xE0', '\xE1', '\a', '*', '\x2', '\x2', '\xE1', '\x32', 
		'\x3', '\x2', '\x2', '\x2', '\xE2', '\xE3', '\a', '+', '\x2', '\x2', '\xE3', 
		'\x34', '\x3', '\x2', '\x2', '\x2', '\xE4', '\xE5', '\a', ']', '\x2', 
		'\x2', '\xE5', '\x36', '\x3', '\x2', '\x2', '\x2', '\xE6', '\xE7', '\a', 
		'_', '\x2', '\x2', '\xE7', '\x38', '\x3', '\x2', '\x2', '\x2', '\xE8', 
		'\xE9', '\a', '}', '\x2', '\x2', '\xE9', ':', '\x3', '\x2', '\x2', '\x2', 
		'\xEA', '\xEB', '\a', '\x7F', '\x2', '\x2', '\xEB', '<', '\x3', '\x2', 
		'\x2', '\x2', '\xEC', '\xED', '\a', '?', '\x2', '\x2', '\xED', '>', '\x3', 
		'\x2', '\x2', '\x2', '\xEE', '\xEF', '\a', '.', '\x2', '\x2', '\xEF', 
		'@', '\x3', '\x2', '\x2', '\x2', '\xF0', '\xF1', '\a', '<', '\x2', '\x2', 
		'\xF1', '\x42', '\x3', '\x2', '\x2', '\x2', '\xF2', '\xF3', '\a', '=', 
		'\x2', '\x2', '\xF3', '\x44', '\x3', '\x2', '\x2', '\x2', '\xF4', '\xF9', 
		'\x5', '\v', '\x6', '\x2', '\xF5', '\xF9', '\x5', '=', '\x1F', '\x2', 
		'\xF6', '\xF9', '\x5', '\x41', '!', '\x2', '\xF7', '\xF9', '\t', '\t', 
		'\x2', '\x2', '\xF8', '\xF4', '\x3', '\x2', '\x2', '\x2', '\xF8', '\xF5', 
		'\x3', '\x2', '\x2', '\x2', '\xF8', '\xF6', '\x3', '\x2', '\x2', '\x2', 
		'\xF8', '\xF7', '\x3', '\x2', '\x2', '\x2', '\xF9', '\x46', '\x3', '\x2', 
		'\x2', '\x2', '\xFA', '\xFC', '\x5', '\x45', '#', '\x2', '\xFB', '\xFA', 
		'\x3', '\x2', '\x2', '\x2', '\xFC', '\xFD', '\x3', '\x2', '\x2', '\x2', 
		'\xFD', '\xFB', '\x3', '\x2', '\x2', '\x2', '\xFD', '\xFE', '\x3', '\x2', 
		'\x2', '\x2', '\xFE', 'H', '\x3', '\x2', '\x2', '\x2', '\x1F', '\x2', 
		'L', 'Q', 'S', '[', '\x66', 'o', 'u', '\x84', '\x87', '\x8D', '\x93', 
		'\x99', '\x9F', '\xA1', '\xA7', '\xA9', '\xB0', '\xB4', '\xBA', '\xC1', 
		'\xC6', '\xC8', '\xCF', '\xD1', '\xDA', '\xDC', '\xF8', '\xFD', '\x3', 
		'\x2', '\x4', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace LentoCore.Parser
